client:
  host: http://localhost:3000
spring:
  datasource:
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:8000/shop_db
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  data:
    rest:
      base-path: /api

okta:
  oauth2:
    client-id: 0oaeqopcw0eGXAHlu5d7
    issuer: https://dev-23230289.okta.com/oauth2/default